Syntax sugars part 2
thedarkcolour/KotlinForForge pull request #55
Opened 2023-01-09 20:12 UTC by tmvkrpxl0

My friend(@PleahMacaka) has suggested me vector deconstructions that even myself wasn't even aware about their existence.
I also added easy conversion between vectors types. this should be adapted for when 4.x comes out though

2023-01-09 20:18 UTC, tmvkrpxl0 commented
I intentionally didn't add Vec3i -> Vec3 conversion as there are multiple "flavors" defined in Vec3 such as `Vec3.atLowerCornerOf(Vec3i)`

2023-01-09 20:37 UTC, PleahMaCaka commented
very uwu function

2023-01-09 20:39 UTC, thedarkcolour commented on kfflib/src/main/kotlin/thedarkcolour/kotlinforforge/forge/vectorutil/Vec2Util.kt
> +public operator fun Vec2.component1(): Float = x
i forgot this was a thing but i love it

2023-01-09 20:42 UTC, thedarkcolour requested changes
Change the fake constructors to extension functions like .toVec3d()
Everything else looks good

2023-01-09 20:42 UTC, thedarkcolour commented on kfflib/src/main/kotlin/thedarkcolour/kotlinforforge/forge/vectorutil/Vector3dUtil.kt
> +public fun Vector3d(other: Vec3): Vector3d {
I think a .toVec3d would be better than a fake constructor

2023-01-09 20:42 UTC, thedarkcolour commented on kfflib/src/main/kotlin/thedarkcolour/kotlinforforge/forge/vectorutil/Vec3iUtil.kt
> +public fun Vec3i(other: Vec3): Vec3i {
I think a .toVec3d would be better than a fake constructor

2023-01-09 20:42 UTC, thedarkcolour commented on kfflib/src/main/kotlin/thedarkcolour/kotlinforforge/forge/vectorutil/Vector3fUtil.kt
> +public fun Vector3f(other: Vector3d): Vector3f {
I think a .toVec3d would be better than a fake constructor

2023-01-09 20:42 UTC, thedarkcolour commented on kfflib/src/main/kotlin/thedarkcolour/kotlinforforge/forge/vectorutil/Vec3Util.kt
> +    return Vec3(other.x, other.y, other.z)
I think a .toVec3 would be better than a fake constructor

2023-01-09 21:02 UTC, tmvkrpxl0 commented on kfflib/src/main/kotlin/thedarkcolour/kotlinforforge/forge/vectorutil/Vec2Util.kt
> +public operator fun Vec2.component1(): Float = x
yep

2023-01-09 23:07 UTC, thedarkcolour approved these changes

2023-01-13 22:53 UTC, tmvkrpxl0 commented
@thedarkcolour So... if all changes are approved, could you merge this?

2023-01-13 23:36 UTC, thedarkcolour commented
I have been busy all week. I can merge it when I get home today, should be back in a couple of hours.

2023-01-14 07:36 UTC, merged